// Code generated by protoc-gen-go.
// source: endpoint.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// API defines the API configuration for a service. It contains a list of
// Endpoints, each with specific information about the endpoint's action.
type API struct {
	Endpoint []*Endpoint `protobuf:"bytes,1,rep,name=endpoint" json:"endpoint,omitempty"`
}

func (m *API) Reset()                    { *m = API{} }
func (m *API) String() string            { return proto1.CompactTextString(m) }
func (*API) ProtoMessage()               {}
func (*API) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *API) GetEndpoint() []*Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

// Endpoint defines extra details about a google.api.http RPC mapping.
type Endpoint struct {
	// unauthenticated must be true if the Endpoint is open to the public. This
	// defaults to false.
	Unauthenticated bool `protobuf:"varint,1,opt,name=unauthenticated" json:"unauthenticated,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto1.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func init() {
	proto1.RegisterType((*API)(nil), "proto.API")
	proto1.RegisterType((*Endpoint)(nil), "proto.Endpoint")
}

func init() { proto1.RegisterFile("endpoint.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 112 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcd, 0x4b, 0x29,
	0xc8, 0xcf, 0xcc, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x46,
	0x5c, 0xcc, 0x8e, 0x01, 0x9e, 0x42, 0xda, 0x5c, 0x1c, 0x30, 0x79, 0x09, 0x46, 0x05, 0x66, 0x0d,
	0x6e, 0x23, 0x7e, 0x88, 0x3a, 0x3d, 0x57, 0xa8, 0x70, 0x10, 0x5c, 0x81, 0x92, 0x09, 0x17, 0x07,
	0x4c, 0x54, 0x48, 0x83, 0x8b, 0xbf, 0x34, 0x2f, 0xb1, 0xb4, 0x24, 0x23, 0x35, 0xaf, 0x24, 0x33,
	0x39, 0xb1, 0x24, 0x35, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x23, 0x08, 0x5d, 0x38, 0x89, 0x0d,
	0x6c, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xb2, 0x50, 0x74, 0xeb, 0x89, 0x00, 0x00, 0x00,
}
